site_name: Word-Search-Generator
site_author: Josh Duncan
copyright: https://github.com/joshbduncan/word-search-generator/blob/main/LICENSE
repo_url: https://github.com/joshbduncan/word-search-generator
edit_uri: edit/main/docs/
repo_name: GitHub
theme: readthedocs
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
