[project]
name = "word-search-generator"
version = "3.5.1"
authors = [{ name = "Josh Duncan", email = "joshbduncan@gmail.com" }]
description = "Make awesome Word Search puzzles"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["puzzles", "games", "word-search"]
license = { text = "MIT License" }
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Games/Entertainment :: Puzzle Games",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]
dependencies = ["fpdf2==2.7.8", "Pillow==11.0.0", "rich==13.6.0"]

[project.urls]
homepage = "https://github.com/joshbduncan/word-search-generator"
documentation = "https://github.com/joshbduncan/word-search-generator/wiki"
repository = "https://github.com/joshbduncan/word-search-generator.git"
changelog = "https://github.com/joshbduncan/word-search-generator/blob/main/CHANGLOG.md"
bug-tracker = "https://github.com/joshbduncan/word-search-generator/issues"

[project.scripts]
word-search = "word_search_generator.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/word_search_generator"]

# TOOL CONFIGURATION

[tool.pytest.ini_options]
addopts = "--cov=word_search_generator"
testpaths = ["tests"]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
implicit_reexport = true

[tool.ruff]
# Same as Black.
line-length = 88

# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

extend-select = ["C4", "I", "SIM", "TCH"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
# fixable = ["B", "I"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py`.
"__init__.py" = ["E402"]
# Ignore `TCH004` in `bitmap.py` (https://github.com/charliermarsh/ruff/issues/2852).
"src/word_search_generator/mask/bitmap.py" = ["TCH004"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.uv]
dev-dependencies = [
    "mypy>=1.11.2",
    "pdfplumber>=0.11.4",
    "pre-commit>=3.8.0",
    "pypdf>=5.0.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=5.0.0",
    "ruff>=0.6.6",
    "pre-commit-uv>=4.1.2",
    "tox>=4.20.0",
    "tox-uv>=1.13.0",
]

[tool.uv.sources]
word-search-generator = { workspace = true }
